### PR TITLE
Smart composite blending 

### PR DESCRIPTION
**Pull request by kalachx**
Added smart blend function to blend dithering and smooth textures without affecting sharpness of the edges. Supports blending transparent objects by utilizing transparency bit from graphics chip.

### CODE REVIEW

**Comment by RobertPeip** [comment]
You are assuming pixeldata(15) to be transparency, but that's wrong.
Bit15 is also used as mask bit for all kind of things.
Transparency is not saved in the vram, but only known at the rendering stage.
We could however store it additionally in a blockram(64Kbyte) if it's really worth it.

What transparency are we even talking about? Pixels on a sprite/texture that are not visiable at all or translucent?

I also see you added the video mixer again. This module cannot work correct if ce_pix is not dividable by 4 of clk_video, which is not the case for PSX. Do you really need this module?

**Comment by kalachx** [comment]
I feared it will not be as easy as using unconnected bit. I made most of this code in one evening the same evening I downloaded the core code so I didn't analyze pixel pipeline at all and just connected wire/signal to where I saw there is unconnected bit from hicolor video mode hoping it will do something interesting and in Spyro it actually worked. Of course it more often just blends random things or whole screen so it is like you rightly pointed out this is not the correct way to do it. Transparency signal is intended only for forcing blending on translucent (alpha blended) textures drawn on top of another textures because they cause dithering patterns to exceed threshold of the filter and cause visible dithering eg. in Crash the moment crash is spawned. On that note the workaround here is disabling dithering for alpha textures. If dithering pattern exceeds filter then it means the same patterns already exist on underlying image and are not really needed when drawing translucent textures. In Silent Hill this 'feature' causes fog to have banding so at least with current implementation it has some issues. There are few blend modes to try out though, maybe it should not be disabled everywhere.

Regarding pull request: I am focusing now on fixing issues with blending because as I started testing more games then it became apparent that darker and more foggy games do show some shimmering/artifacts on the edges. I already changed blend function to be more correct and it is included in build from dithering topic and is the default blend mode and old blending is called "alternate blend". Blend from last commit here has major flaw in that it moves blended pixels to the left. New method does not move pixels and is better at removing dithering because it uses 3 pixels for blending. It more strongly blends pixels  but I actually like how clean it makes games look while not making them look blurry. It is also much better at removing dithering. Left edge needs more work while right edge seems to be already handled correctly... in other words it is still work in progress. I will commit tomorrow after I remove unnecessary test wires/signals.

As for video mixer I tried to use it but it didn't do much. I forgot to comment it out.

**Comment by RobertPeip** [comment]
Great, let me know when you have it at a state i should try.

If you have any question or need help, just tell me.

**Comment by kalachx** [comment]
I made some changes to how blending algorithm works to resolve issues with dither patterns being visible on edges of objects in darker games and blended pixels moving one/half pixel to the left. Now blending is applied closer to the edges but does not blend edges from either side. Blending is now much stronger (and kinda looks like what 3dfx Voodoo1 did!) and because of that I also added option to weaken it somewhat to make effect more neutral. Resulting image has dithering but is now actually closer to what I remember PSX games looking like on somewhat blurry TV's I had in the late 90's. I also included few dither patterns. Not sure if you are interested in having such feature but imho because any of these patterns has its unique look and original PSX pattern isn't always the best I thought it might be fun for people to play with them because it is quite fun for me. A lot of games really look better with alternative patterns and overall grainy PSX look is still there.

As a workaround for the issue with translucent polygons exceeding filter and having noticeable dither pattern I added option to disable dithering on translucent polygons. It seems to work fairly well in most games. Silent Hill is of course the exception and in some other games disabling this dithering might cause slightly more visible banding on some translucent textures so perhaps more effort is needed to tweak this effect. I will attempt to check if using different pattern (also with smaller values) for translucent textures would yield better results or if there is a way to apply dithering to some alpha blending modes and not to others. The use of block ram to force blending on pixels which have translucent polygons is still an option I will want to eventually explore.

My understanding of the gpu pipeline is that data flows from one stage to the next and process one pixel at a time one stage per clock cycle. Then as I understand it is saved to SDRAM and from there it either goes back to the pipeline eg. to apply another polygon (presumably translucent if all culling is done correctly) or to the screen. I would need to use the same memory address for block memory as used by SDRAM if I wanted to save more bits of information. Now my understanding is that 64Kbyte size you mentioned is because then I would not need to worry about where this data goes and what happens to it, otherwise if I assumed pipeline_x and pipeline_y are always related to back buffer it would either need to always be the same memory location in each game or I would need to know how to recalculate memory location to pixels on screen making whole thing much much harder and error prone. Is this correct?

I will probably try with 64KB and then try to limit it to 32KB (back and front buffers address probably differ in one significant bit) and then 16KB. I do not think 3D games should use resolutions larger than 512x256 though I am not really sure, maybe some do. Other option I was considering is re-use now free SDRAM module and try getting another 16-bit worth of data, at least before trying to do the same on first SDRAM which option might be above my HDL skills for a longer while. My naive understanding is that it should be possible to use the same signals to control two sets of SDRAM chips and send/receive different data from each...

**Comment by kalachx** [comment]
I tested the idea for using reverse dither pattern for additive alpha-blending and it actually works amazingly well. What was however surprising was that it actually also works in Silent Hill and produces much smoother fog gradients. So far all games I tested look better with this option. Multiple alpha-blended textures  and alpha blended texture that is contrasting with the background can still exceed blending filter threshold but overall for most cases dithering patterns are reduced considerably.

It required adding additional dithering calculation. I was not sure if I can be sure at stage 3 which dithering pattern I should use so I added new variables stage3_d(rgb) with reversed dithering pattern and if/else at stage 4 during alpha blending. If there is no reason (it looks like it should not be but I am not 100% sure...) to doubt draw_mode at stage 3 then code can be simplified and only affect stage2_ditherAdd calculation.

**Comment by birdybro** [comment]
I tested your build just now. Valkyrie profile's opening is a good test, there are a lot of artifacts that are not present in a typical composite setup that show up, this sort of test might help you fine tune the concept more.

https://user-images.githubusercontent.com/16388068/150726649-ef5e20ec-6782-4bf7-b265-a021c73574e0.mp4

**Comment by RobertPeip** [comment]
What's the result of your research? Sorry I was busy and didn't follow every change...

**Comment by kalachx** [comment]
PR got deleted because yesterday I tried to refactor the code to remove features not related to dithering filter and move it to separate branch so I could develop and release it on main while keeping the dithering filter separately on dedicated branch. I added too many features to this PR and some of them looked like a quick hacks because they were. I tried to rename branches and PR got deleted and it still points to "main" even though main is different branch now renamed to main... in other words technical issues.

I am still working on this and managed to resolve issues with composite still having dithering mentioned by birdybro. More specifically to make "composite" look more like composite but not by making it more blurry than what it already was and rather utilizing detection and blurring some parts more than others. I will make separate PR for dithering filter tomorrow after removing debug code.

Separately I will make PR for alpha blending fix. Need to check if there is nicer way to write it.

Last feature related to changing dithering patterns is not really universal fix. Some games look better with one pattern, some with other and some (eg. Soul Reaver) it is mixed bag so I am dropping it. I will add it to my own release along maybe with some other dithering experiments I want to try out.

**Pull request closed without merging**
